fibo completed
AleksandrMac/GeekBrains pull request #12
Opened 2020-12-11 07:04 UTC by AleksandrMac

написал фибо чрез рекурсию, как и просили)
отправил запись полученных значений в мапу, навреное потому что записать несколько раз в мапу и вывести один раз ее на печать быстрее, чем каждый раз выводить на печать полученное значение.

2020-12-14 16:35 UTC, rumyantseva requested changes
Принимаю рекурсию, но вторая часть задания не выполнена. Идея заключается в том, чтобы на каждом шаге рекурсии "запоминать" в мапе вычисленное значение. Тогда перед тем, как вычислять значение заново на следующем шаге, можно сначала посмотреть не было ли оно уже вычислено и запомнено. Предлагаю еще подумать над второй частью задания, в четверг разберем решение в конце урока.

2020-12-15 06:34 UTC, AleksandrMac commented
Доработал алгоритм получения числа, с сохранением чисел в мапу, и до заполнением мапы по вызову

2020-12-15 07:06 UTC, AleksandrMac commented
еще немного поправил

2020-12-18 21:13 UTC, rumyantseva reviewed
Честно говоря, не поняла, зачем здесь отдельно нужен геттер и отдельно сеттер.

2020-12-18 21:13 UTC, rumyantseva commented on Go/Go_level_1/lesson4/fibo.go
> +//получаем значение числа фибоначи
С форматом документации познакомимся попозже, но вообще стандартный комментарий к экспортируемым сущностям в Go принято начинать с имени этой сущности, т.е. в Вашем случае будет что-то вроде

```
// Get вычисляет ...
```

Подробнее можно почитать здесь: https://blog.golang.org/godoc

Еще, кстати, методы-геттеры тоже не приняты :) Вот здесь про это написано: https://golang.org/doc/effective_go.html#Getters

В Вашем случае по-гошному метод должен называться Fibo.

2020-12-21 05:02 UTC, AleksandrMac commented
Спасибо за замечания, все исправил: 
- поправил комментарии;
- поправил наименование Геттера
- убрал сеттер как отдельный метод

2021-02-19 08:19 UTC, merged