lesson5 completed
AleksandrMac/GeekBrains pull request #13
Opened 2020-12-21 06:13 UTC by AleksandrMac

Исправил функцию проверки валидности сканирования данных,

2020-12-31 14:56 UTC, rumyantseva requested changes

2020-12-31 14:56 UTC, rumyantseva commented on Go/Go_level_1/lesson2/less2.go
> +		return fmt.Println("Please input correct", reflect.TypeOf(param))
По-моему, у Вас тут ошибка компиляции будет :) В сигнатуре два возвращаемых результата, а у Вас только один здесь.

2021-01-03 13:32 UTC, AleksandrMac commented on Go/Go_level_1/lesson2/less2.go
> +		return fmt.Println("Please input correct", reflect.TypeOf(param))
Нет, там ошибки компиляции нет, т.к. err инициализируется выше, и второй возвращаемый параметр берется автоматически(специфика го), но в этом месте ретурн в принципе не нужен, т.к. по идее должно произойти зацикливание до момента валидного ввода.

 У меня теперь вопрос, в этом примере из за цикла for просьба "ввести правильное число" печатается два раза, вместо одного, можно этот момент как то решить?

2021-01-03 14:31 UTC, rumyantseva commented on Go/Go_level_1/lesson2/less2.go
> +		return fmt.Println("Please input correct", reflect.TypeOf(param))
Ошибки компиляции тут не будет, потому что сигнатура у результатов fmt.Println такая же, как и у вашей функции (а не потому, что что-то там инициализируется выше). И это все-таки неправильно. Что такое count в вашей функции и что возвращает первым параметром fmt.Println? Вы уверены, что это однородные данные?

В каком случае просьба печатается два раза вместо одного? Запустила у себя, у меня напечаталась по разу на каждый вызов validScan из функции main.

Вообще, конечно, лучше validScan переписать. Сейчас довольно сложно понять, что хотел автор. Подумайте, в каких случаях функция должна возвращать ошибку, а в каких не должна, и должен ли Println быть частью этой функции или частью той функции, которая вызывает validScan.

2021-01-05 10:19 UTC, AleksandrMac commented on Go/Go_level_1/lesson2/less2.go
> +		fmt.Println("Please input correct", reflect.TypeOf(param))
validScan возвращает ошибку в случае когда тип вводимых параметров не соответствует типу param, return из последней строчки функции был удален, еще в прошлый раз(не там комментарий оставил, поэтому вы не заметили), так как функция зацикливается до момента, пока пользователь не введет  корректные данные.

count - возвращает количество успешно считанных аргументов, разделенных пробелом или 'v', но он всегда возвращает один аргумент, либо 0, если введенные данные не соответствуют типу переменной переданной в param.

Два раза Println срабатывает, когда вводишь некорректное значение, и два раза потому что строка разбивается на сам символ, и на символ окончания строки, и пытается преобразовать их оба. Я как понял.

Надеюсь ясно выразился))
P.S. Мозг ушел на выходные, возвращаться не хочет...

2021-01-05 10:25 UTC, AleksandrMac commented on Go/Go_level_1/lesson2/less2.go
> +			break
убрал из сигнатуры возвращаемые значения, т.к. в данной ситуации они лишены смысла, return заменил на break, для выхода из цикла в случае удачного ввода данных

2021-02-19 08:21 UTC, merged