Js lesson4
AleksandrMac/GeekBrains pull request #4
Opened 2020-11-06 03:29 UTC by AleksandrMac

2020-11-06 16:17 UTC, Om1X requested changes

2020-11-06 16:17 UTC, Om1X commented on JS/lesson4/task1.html
> +        return obj
ок, но можно еще короче решение сделать

2020-11-06 16:17 UTC, Om1X commented on JS/lesson4/task3.html
> +    };
Зачем все это усложнение? Достаточно просто обозначить массив с объектами (goods: `[{title: 'Good title', price: 100, quantity: 3}, .... ]`) товаров и все.

2020-11-09 02:20 UTC, AleksandrMac commented on JS/lesson4/task3.html
> +    };
`function  integerToObjectFor ( number , obj =  { } )  {
        const  digitNumber  =  [ 'единицы' ,  'десятки' ,  'сотни' ] ;
        if  ( ( число  >  999  ||  число  <  0 )  &&  Object . keys ( obj ) . length  ===  0 )
            консоль . log ( "Необходимо число в интервале [0, 999]" ) ;
        еще
            for ( let  i  =  0 ,  num  =  number ;  num  >  0 ;  num  =  Math . floor ( num / 10 ) ,  i ++ )     obj [ digitNumber [ i ] ]  =  num % 10 ;
        return  obj ;
    }`

Реализовал функцию через цикл FOR

2020-11-09 02:27 UTC, AleksandrMac commented on JS/lesson4/task1.html
> +    function integerToObjectFor(number, obj = {}) {
@Om1X , > ок, но можно еще короче решение сделать
Реализовал через цикл FOR

2020-11-09 02:38 UTC, AleksandrMac commented on JS/lesson4/task3.html
> +    };
[https://github.com/AleksandrMac/GeekBrains/pull/4/commits/20f5b5a9ee98de44c16aa18ca13bf2d2f002c343](url)
Реализовал через цикл FOR

2020-11-09 02:41 UTC, AleksandrMac commented on JS/lesson4/task1.html
> +        return obj
[https://github.com/AleksandrMac/GeekBrains/pull/4/commits/20f5b5a9ee98de44c16aa18ca13bf2d2f002c343](url)
реализовал через цикл FOR

2020-11-09 02:49 UTC, AleksandrMac commented on JS/lesson4/task1.html
> +    function integerToObjectFor(number, obj = {}) {
https://github.com/AleksandrMac/GeekBrains/pull/4#discussion_r518853605

2020-11-09 03:15 UTC, AleksandrMac commented
```
    function integerToObjectFor(number, obj = {}) {
        const digitNumber = ['единицы', 'десятки', 'сотни'];
        if ((number > 999 || number < 0) && Object.keys(obj).length === 0)
            console.log("Необходимо ввести число в интервале [0, 999]");
        else
            for(let i = 0, num = number; num > 0; num = Math.floor(num/10), i++)    obj[digitNumber[i]] = num%10;
        return obj;
    }
```

[https://github.com/AleksandrMac/GeekBrains/pull/4/commits/20f5b5a9ee98de44c16aa18ca13bf2d2f002c343](url)

реализовал через цикл FOR

2020-11-14 00:19 UTC, AleksandrMac reviewed
-

2020-11-14 00:19 UTC, AleksandrMac commented on JS/lesson4/task1.html
> +    }
@Om1X , https://github.com/AleksandrMac/GeekBrains/pull/4#discussion_r518853605

Реализовал через цикл FOR

2020-11-14 00:19 UTC, AleksandrMac commented on JS/lesson4/taskLesson4.md
> +4. \* Подумать над глобальными сущностями. К примеру, сущность «Продукт» в интернет-магазине актуальна не только для корзины, но и для каталога. Стремиться нужно к тому, чтобы объект «Продукт» имел е
@Om1X , https://github.com/AleksandrMac/GeekBrains/pull/4#discussion_r518855462

Если посмотреть на эту задачу, хоть она была и не обязательна, то я создал отдельно объект продукт, без свойства количества, так как это свойство, например в каталоге ему не нужно, далее шагая в сторону укрупнения, создал объект "позиция корзины", к которой можно применить, например индивидуальное свойство "скидки",  и далее идет самый крупный  объект корзины, в ней так же может быть свойство "скидка", но уже общая на итоговую стоимость.

И чтобы в будущем, при увеличении масштаба задачи, не переписывать код, я решил его изначально разложить на более мелкие объекты, четко отвечающими своим задачам.

2020-12-07 00:06 UTC, merged